name: bogsi-quotable

services:
  web:
    environment:
      QuotableDb__Server: database
      QuotableDb__Port: 8084
      QuotableDb__DatabaseName: quotable-db
      QuotableDb__UserName: quotable
      QuotableDb__Password: quotable123
      Messaging__Address: messaging
      Messaging__Port: 8085
      Messaging__UserName: quotable
      Messaging__Password: quotable 
      Valkey__Address: caching
      Valkey__Port: 8086
