name: bogsi-quotable

services:
  aspnet-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bogsi-quotable-aspnet-backend:latest
    container_name: aspnet-backend
    networks:
      - quotable-network
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  quotable-network: