### Default Request 
### An example of a working request. 
# @name example-request

DELETE {{host-name}}/api/v1/quotes/8c9853fb-beaf-4296-a8b7-415f49a7caf1 HTTP/1.1
Accept: application/json



### Working Request
### Use this request to test. 
# @name test-request

@Public-Id = d81df0e7-ddfe-406c-bd2c-58d6b28c9b50

DELETE {{host-name}}/api/v1/quotes/{{Public-Id}} HTTP/1.1
Accept: application/json