### Default Request 
### An example of a working request. 
# @name example-request

GET {{host-name}}/api/v1/quotes/64a140bd-bdfa-46e8-8cbf-169703626004 HTTP/1.1
Accept: application/json



### Working Request
### Use this request to test. 
# @name test-request

@Public-Id = 64a140bd-bdfa-46e8-8cbf-169703626004

GET {{host-name}}/api/v1/quotes/{{Public-Id}} HTTP/1.1
Accept: application/json
