@Bogsi.Quotable_HostAddress = http://localhost:8080

### Default Request 
### An example of a working request. 

GET {{Bogsi.Quotable_HostAddress}}/api/quotes/fffc0d53-441e-44dc-b7f9-849393a78c8f

Accept: application/json



### Working Request
### Use this request to test. the other two serve more as examples or guidelines.  

@Public-Id = fffc0d53-441e-44dc-b7f9-849393a78c8f

GET {{Bogsi.Quotable_HostAddress}}/api/quotes/{{Public-Id}}

Accept: application/json
