### Default Request 
### An example of a working request. 
# @name example-request

PUT {{host-name}}/api/v1/quotes/ef57e67e-e462-4a19-ab62-27a35d784cb3 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "value" : "Quote value comes here."
}



### Working Request
### Use this request to test.
# @name test-request

@Public-Id = ef57e67e-e462-4a19-ab62-27a35d784cb3

PUT {{host-name}}/api/v1/quotes/{{Public-Id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

< ./request-bodies/UpdateQuote.json