// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bogsi.Quotable.Persistence.Migrations.Saga
{
    /// <inheritdoc />
    public partial class Add_Versioning : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "SagaFailed",
                schema: "Saga",
                table: "UpdateQuoteSagaData",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "Saga",
                table: "UpdateQuoteSagaData",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<bool>(
                name: "SagaFailed",
                schema: "Saga",
                table: "DeleteQuoteSagaData",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "Saga",
                table: "DeleteQuoteSagaData",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<bool>(
                name: "SagaFailed",
                schema: "Saga",
                table: "CreateQuoteSagaData",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "Saga",
                table: "CreateQuoteSagaData",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SagaFailed",
                schema: "Saga",
                table: "UpdateQuoteSagaData");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "Saga",
                table: "UpdateQuoteSagaData");

            migrationBuilder.DropColumn(
                name: "SagaFailed",
                schema: "Saga",
                table: "DeleteQuoteSagaData");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "Saga",
                table: "DeleteQuoteSagaData");

            migrationBuilder.DropColumn(
                name: "SagaFailed",
                schema: "Saga",
                table: "CreateQuoteSagaData");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "Saga",
                table: "CreateQuoteSagaData");
        }
    }
}
