// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bogsi.Quotable.Persistence.Migrations.Saga
{
    /// <inheritdoc />
    public partial class Initial_Saga : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Saga");

            migrationBuilder.CreateTable(
                name: "CreateQuoteSagaData",
                schema: "Saga",
                columns: table => new
                {
                    CorrelationId = table.Column<Guid>(type: "uuid", nullable: false),
                    CurrentState = table.Column<string>(type: "text", nullable: false),
                    PublicId = table.Column<Guid>(type: "uuid", nullable: false),
                    QuoteCreated = table.Column<bool>(type: "boolean", nullable: false),
                    CacheCreated = table.Column<bool>(type: "boolean", nullable: false),
                    SagaFinalized = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CreateQuoteSagaData", x => x.CorrelationId);
                });

            migrationBuilder.CreateTable(
                name: "DeleteQuoteSagaData",
                schema: "Saga",
                columns: table => new
                {
                    CorrelationId = table.Column<Guid>(type: "uuid", nullable: false),
                    CurrentState = table.Column<string>(type: "text", nullable: false),
                    PublicId = table.Column<Guid>(type: "uuid", nullable: false),
                    QuoteDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    CacheCleaned = table.Column<bool>(type: "boolean", nullable: false),
                    SagaFinalized = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeleteQuoteSagaData", x => x.CorrelationId);
                });

            migrationBuilder.CreateTable(
                name: "UpdateQuoteSagaData",
                schema: "Saga",
                columns: table => new
                {
                    CorrelationId = table.Column<Guid>(type: "uuid", nullable: false),
                    CurrentState = table.Column<string>(type: "text", nullable: false),
                    PublicId = table.Column<Guid>(type: "uuid", nullable: false),
                    QuoteUpdated = table.Column<bool>(type: "boolean", nullable: false),
                    CacheUpdated = table.Column<bool>(type: "boolean", nullable: false),
                    SagaFinalized = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UpdateQuoteSagaData", x => x.CorrelationId);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CreateQuoteSagaData",
                schema: "Saga");

            migrationBuilder.DropTable(
                name: "DeleteQuoteSagaData",
                schema: "Saga");

            migrationBuilder.DropTable(
                name: "UpdateQuoteSagaData",
                schema: "Saga");
        }
    }
}
