// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Bogsi.Quotable.Persistence.Migrations.Quotable
{
    /// <inheritdoc />
    public partial class InitialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Quotable");

            migrationBuilder.CreateTable(
                name: "Quotes",
                schema: "Quotable",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Value = table.Column<string>(type: "character varying(1255)", maxLength: 1255, nullable: false),
                    PublicId = table.Column<Guid>(type: "uuid", nullable: false),
                    Created = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()"),
                    Updated = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Quotes", x => x.Id);
                });

            migrationBuilder.InsertData(
                schema: "Quotable",
                table: "Quotes",
                columns: new[] { "Id", "PublicId", "Value" },
                values: new object[,]
                {
                    { 1, new Guid("e59726ec-01d8-4d82-93f7-f414d05c80cd"), "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn." },
                    { 2, new Guid("9d7184b0-591f-49c1-aeae-e5ebdad466a5"), "That is not dead which can eternal lie, And with strange aeons even death may die." }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Quotes",
                schema: "Quotable");
        }
    }
}
